#ifndef _CODE_
#define _CODE_

extern const unsigned char menu_pfg[];
extern const unsigned char menu_par_ee_addr[];
extern const unsigned char *const pmenu_par_item[];
extern const int *const pmenu_par_max[];
extern const int *const pmenu_par_min[];
extern const unsigned char *const pmenu_par_dot[];
extern unsigned char menu_par_num[];
extern const unsigned int menu_password[];

extern const unsigned char menu_item1[][4];
extern const unsigned char menu_item2[][4];
#define TMAX 2
#endif




